# Generated by Django 5.0.7 on 2024-08-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
