# Generated by Django 5.0.7 on 2024-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=15),
        ),
    ]
