# Generated by Django 5.0.7 on 2024-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_questionanswer_delete_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='questions',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='questionstype',
            new_name='questions_type',
        ),
        migrations.RenameField(
            model_name='questionstype',
            old_name='questiontype',
            new_name='questions_type',
        ),
    ]
