# Generated by Django 5.0.7 on 2024-09-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_alter_questionanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionsAnswerType', to='Questions.questionstype'),
            preserve_default=False,
        ),
    ]
